# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado_test/MIPS_CPU/MIPS_CPU.cache/wt [current_project]
set_property parent.project_path D:/vivado_test/MIPS_CPU/MIPS_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado_test/MIPS_CPU/MIPS_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/vivado_test/MIPS_CPU/instructions.coe
read_verilog -library xil_defaultlib {
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/ALU.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/Counter.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/Mux.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/PCreg.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/RAM.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/Regfiles.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/Rom.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/clock.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/clock_cpu.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/control.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/display.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/signextension.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/to10.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/zeroextension_1.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/zeroextension_2.v
  D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/MipsCPU.v
}
read_ip -quiet D:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/vivado_test/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_test/MIPS_CPU/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/vivado_test/MIPS_CPU/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MipsCPU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MipsCPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MipsCPU_utilization_synth.rpt -pb MipsCPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
